{% set version = "2.5.0-rc1" %}
{% set sha256 = "6535b3d3e9cfa492176660f80bcab76a6fb703f59bee578dc62f7b9793b9e467" %}

package:
  name: singularity
  version: {{ version.replace("-", ".") }}

source:
  fn: singularity-{{ version }}.tar.gz
  url: https://github.com/singularityware/singularity/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - toolchain
    - autoconf
    - automake
    - libtool
    - m4
    - pkg-config
    - libarchive 3.3.2

  run:
    - libarchive 3.3.2

test:
  commands:
    - which singularity
    - singularity --help

about:
  home: http://singularity.lbl.gov/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE-LBNL.md
  summary: "Singularity: Application containers for Linux"

  description: |
    Singularity is a container platform focused on supporting "Mobility of
    Compute"

    Mobility of Compute encapsulates the development to compute model where
    developers can work in an environment of their choosing and creation and
    when the developer needs additional compute resources, this environment
    can easily be copied and executed on other platforms. Additionally as the
    primary use case for Singularity is targeted towards computational
    portability, many of the barriers to entry of other container solutions do
    not apply to Singularity making it an ideal solution for users (both
    computational and non-computational) and HPC centers.

  dev_url: https://github.com/singularityware/singularity
  doc_url: http://singularity.lbl.gov/user-guide

extra:
  recipe-maintainers:
    - bgruening
    - jakirkham
